### ISSUE TITLE
Edits to a signature not showing?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#160] opened 2023-03-02 09:02 UTC
I just made several corrections to invalid taxonomic names in study https://bugsigdb.org/Study_249. One of these, for example, was changing a "Clostridium XI" to 186804 ([Peptostreptococcaceae](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=186804&lvl=3&p=has_linkout&p=blast_url&p=genome_blast&keep=1&srchmode=1&unlock) ) in https://bugsigdb.org/Study_249/Experiment_3/Signature_1. Here is a screenshot showing what edit mode for that signature now looks like:

![image](https://user-images.githubusercontent.com/639942/222379747-77953640-e7df-40d6-8835-bc90c9b5ca77.png)

But after saving, here is how this signature displays - it does not display _Peptostreptococcaceae_:

![image](https://user-images.githubusercontent.com/639942/222379918-4cf43437-fb6e-41b2-b48c-ba0aad7f61ad.png)

I made several other edits to signatures in this study that are also not displaying, although I'm not sure how to view history of signatures or experiments rather than only for the study (a question for another issue)

**Comment by lwaldron** [comment] 2023-03-02 09:04
I'm leaving behind one edit in this study still to be done: in Experiment 4 / Signature 1, g__Turicella should be 1716.

**Comment by lwaldron** [comment] 2023-03-02 09:19
I noticed this issue in a signature that I haven't edited recently: https://bugsigdb.org/Study_356/Experiment_7/Signature_2 has both g__clostridium_XI and 186804 entered, but it is only displaying g__clostridium_XI (a blank space is displayed where Peptostreptococcaceae should be, like in the first row of the screenshot above):

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/639942/222384738-08c2c31e-c845-42ad-b878-769198813f23.png">


<img width="247" alt="image" src="https://user-images.githubusercontent.com/639942/222384521-84167672-e404-4ccc-96c3-ae7f11174a29.png">

**Comment by lwaldron** [comment] 2023-03-02 09:30
FWIW, this does not seem to affect all signature edits - for example I just added 31979 to  https://bugsigdb.org/Study_356/Experiment_2/Signature_1, and it immediately displayed correctly as _Clostridiaceae_.

**Comment by tosfos** [comment] 2023-03-02 23:12
Interesting. The wiki is trying to display the name, but it thinks the name is a blank string. I haven't verified, but I suspect there is something special about the data NCBI is sending us for 186804.

**Comment by tosfos** [comment] 2023-03-05 15:50
When we checked it, the display was fine. We're not sure what the cause was, and we're not able tor reproduce it. I suggest closing, in the hope that it was a one-time glitch, and seeing if it happens again.

**Closed** 2023-04-18 14:25 UTC
Labels: bug
