### ISSUE TITLE
Missing Data in CSVs

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/BugSigDB#238] opened 2024-08-07 22:22 UTC
Hi @tosfos 

There seem to be some data missing from the CVS available at https://bugsigdb.org/Help:Export at least for the studies and signatures. It's not clear what is common denominator.

For example, if you look at https://bugsigdb.org/Study_983 and https://bugsigdb.org/Study_992, both studies, their experiments, and signatures are reviewed; however, looking at their results in the respective downloads, both studies are missing reviewers and their signatures are missing reviewers. A revision editor is missing for Signature 1 for Study 983. The Experiments for these two studies appears correct; however, I don't see all the experiments in the experiment CSV for https://bugsigdb.org/Study_1015 but that might be because I can't download the complete file.

@cmirzayi first noticed these issues downstream in https://github.com/waldronlab/BugSigDBExports/issues/32. They appear to be data that users don't enter.

Could you take a look?

**Comment by cmirzayi** [comment] 2024-08-22 14:14
Just chiming in to say that resolving this is fairly critical now. We have multiple student projects that are making use of these data and it's alarming that they are not able to obtain consistent, complete data.

**Comment by tosfos** [comment] 2024-08-27 18:14
We currently have a bunch of GitHub issues that have the same cause - incomplete semantic data. That can either manifest itself while viewing the wiki or downloading the CSV, but the cause is the same.

1. This one
2. https://github.com/waldronlab/BugSigDB/issues/196
3. https://github.com/waldronlab/BugSigDB/issues/234
4. https://github.com/waldronlab/BugSigDB/issues/209
5. https://github.com/waldronlab/BugSigDB/issues/221

Can everything be combined into one issue?

**Comment by jwokaty** [comment] 2024-08-27 19:35
I'm fine with combining the issues so long as we don't lose track of things we should check to determine if the problem has been resolved.  Should this be the primary issue or another?

**Comment by tosfos** [comment] 2024-08-28 22:18
I'll close a bunch.

**Closed by tosfos** 2024-08-28 22:18 UTC

**Comment by tosfos** [comment] 2024-08-28 22:20
https://github.com/waldronlab/BugSigDB/issues/221
