### ISSUE TITLE
data transfer unit tests

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#41] opened 2020-10-30 15:02 UTC
After transferring data from the spreadsheet to the wiki, then exporting from the wiki, do some sanity checks that the data still match the original spreadsheet. Doesn't have to be exhaustive, but, for example:
1. All the studies / PMIDs are still present
2. Each study still has the same experiments
3. Each experiment still has the same signatures
4. Each signature still has the same taxa

A few dplyr joins on the two tables, with checks on the joined columns, might be adequate. Otherwise, it could be hard to detect an error in the data transfer and hard to fix after the wiki is in use.

**Comment by tosfos** [comment] 2021-03-08 17:06
Any thoughts on this, please?

**Comment by lwaldron** [comment] 2021-03-08 20:52
It seems better to keep the superkingdoms; it could be useful to filter by Eukaryotes, Bacteria, Archea, Virus.

**Comment by lgeistlinger** [comment] 2021-03-13 21:39
@tosfos status update on this - it looks as if we are getting closer, with 16 signatures remaining where imported and exported NCBI Taxonomy IDs are not exactly the same.
Those are exclusively cases where the export seems to contain additional NCBI IDs, but this might be by design or related to the issue with the taxonomy levels above?

signature	setdiff.import	setdiff.export	import	export
**Study 5/Experiment 1/Signature 1**	NA	1257,32066,84642	848,32067,84107,1380,84162,133925,1839,1268,32207,2049,1654,1678,186826,1300,1301,186827,46123,526525,128827,118747,123375,31977,39948,29465,970,82202,186803,43996,265975,830,186806,1730,203491,203490,1129771,203492,204441,186650,206351,135624,642,613,213118,213119,893,29547,213849,72294,194,156973,195950,838,1016,52228,543311,653683	848,32067,84107,1380,84162,133925,1839,1268,32207,2049,1654,1678,186826,1300,1301,186827,46123,526525,128827,118747,123375,31977,39948,29465,970,82202,186803,43996,265975,830,186806,1730,1257,32066,203491,203490,1129771,203492,204441,186650,206351,135624,84642,642,613,213118,213119,893,29547,213849,72294,194,156973,195950,838,1016,52228,543311,653683
**Study 18/Experiment 1/Signature 1**	NA	351091,89153	816,1485,841,1578,166486,106588,168384,1263067,1605,360807,1239,459786,1730,830,1263,1017280,572511,189330,244127,292632,216851,203691,203682,200918,32066,508458,1117,28890,200795,1351,29347	816,1485,841,1578,166486,106588,168384,1263067,1605,360807,1239,459786,1730,830,1263,1017280,572511,189330,244127,292632,216851,203691,203682,200918,32066,508458,1117,28890,200795,1351,351091,89153,29347
**Study 56/Experiment 3/Signature 1**	NA	135858,33882,1378	976,200643,526524,85020,31953,84107,815,171551,186806,186803,31977,128827,69277,433,267408,88138,57493,2053,1678,1380,102106,162291,574697,156973,375288,836,33042,189330,841,459786,1263,904,39948,191303,61170,838,1730,125216	976,200643,526524,85020,31953,84107,815,171551,186806,186803,31977,128827,69277,433,267408,88138,57493,2053,1678,1380,102106,162291,574697,156973,375288,836,33042,189330,841,459786,1263,904,39948,135858,191303,61170,838,33882,1378,1730,125216
Study 150/Experiment 1/Signature 2	NA	186804,203491	841,970,838,1716,1730,109326,543311,1506553,157,59735,194,32067,475,1257,713,848,29465,836,32207,724,482,363464,1653,85007,95818,136,137,203692,72294,29547,213849,1129771,468,203492,203490,32066,186801,186802,909929,909932,31977	841,970,838,1716,1730,109326,543311,1506553,157,59735,194,32067,475,1257,713,848,29465,836,32207,724,482,363464,1653,85007,95818,136,137,203692,72294,29547,213849,1129771,468,186804,203492,203490,32066,203491,186801,186802,909929,909932,31977
Study 165/Experiment 1/Signature 2	NA	174708,32207,186806	74201,48461,239934,203494,203557,995019,577310,91061,186826,80840,28216,33958,1578,133925,649777,508458,649776,1243,638847,29547,2753,649775,213849,1427376,209,72293,191393,68337,248038,1357,200930,580024,191394,1268,1730,265975	74201,48461,239934,203494,203557,995019,577310,91061,186826,80840,28216,33958,1578,133925,649777,508458,649776,1243,638847,29547,2753,649775,213849,1427376,209,72293,191393,68337,248038,1357,200930,580024,191394,174708,32207,1268,1730,186806,265975
Study 178/Experiment 3/Signature 1	NA	22,39948,1378,206349	1239,91061,186826,1300,1301,31977,1257,186804,201174,33958,1578,31953,1678,85004,80840,206351,481,482,543,91347,117563,186828,29465,92793,149698,75682,1263,42255,84997,84996,1743,31957,267890,135622,407,119045,841,541000,572511,70774,119069,204475,33042	1239,91061,186826,1300,1301,31977,1257,186804,201174,33958,1578,31953,1678,85004,80840,206351,481,482,543,91347,117563,186828,29465,92793,149698,75682,1263,42255,84997,84996,1743,31957,267890,22,135622,407,119045,39948,1378,841,541000,572511,70774,119069,206349,204475,33042
Study 274/Experiment 8/Signature 1	NA	NA	1465756,2701,1578,165779,437755,28125,1678,47770	165779,1678,2701,1578,47770,437755,1465756,28125
Study 285/Experiment 3/Signature 1	NA	823,39778	186802,872,541000,33024,239935,990719,119852,186803,47678,84107,35832,310297,165179,1263,135858,729,158846,33042,1678,2172,33038,80864,906,113286,1730,853,33035,904,28116,189330,40544,1380,363265	186802,872,541000,33024,239935,990719,119852,186803,47678,84107,35832,310297,165179,1263,135858,729,158846,33042,1678,2172,33038,80864,906,113286,1730,853,33035,904,28116,189330,40544,1380,363265,823,39778
Study 286/Experiment 1/Signature 2	NA	NA	1239,572511,1407607,574697,207244,102106,204516,1263,328814,39488,39496,1852369	328814,39488,207244,572511,574697,102106,39496,1239,1407607,1852369,204516,1263
Study 295/Experiment 1/Signature 1	NA	119060,1257,1678,32066	128827,526525,526524,745,212791,712,135625,1407607,80865,1485,33042,35832,1654,995019,1348911,1263,574697,80864,40544,841,572511,171550,239759,33024,2049,204475,39948,544448,31969,206349,119069,70774,186804,906,1200657,541000,186803,168808,1129771,203491,203490,186801,186802	128827,526525,526524,745,212791,712,135625,1407607,80865,1485,33042,35832,1654,995019,1348911,1263,574697,80864,40544,841,572511,171550,239759,33024,2049,204475,39948,544448,31969,206349,119069,70774,119060,1257,186804,906,1200657,1678,541000,186803,168808,1129771,203491,32066,203490,186801,186802
Study 307/Experiment 1/Signature 2	NA	135858,1318,729	1239,171549,823,35833,360807,28118,186803,1955243,1506,853,40519,328814,239759,216851,487175,1913682,1680,328813,572511,459786,1945593,100883,214856,544645,261299,541000,28026,186802,1730,28117,574697,487174,39485,39486,1485	1239,171549,823,35833,360807,28118,186803,1955243,1506,853,40519,328814,239759,216851,487175,1913682,1680,328813,572511,459786,1945593,100883,214856,544645,261299,541000,28026,186802,1730,28117,574697,487174,39485,135858,1318,39486,1485,729
Study 338/Experiment 2/Signature 1	NA	33024,80840,506	194,191303,1502,713,1129771,186828,117563,2382,43675,186804,416916,727,1268,32207,31979,1301,1300,186826,387090,91061,39778,29465,158846,729,724,203492,203491,203490,32066,848,135625,538998,28050,28216,40544,165179,1224,36835,33038,1263076	194,191303,1502,713,1129771,186828,117563,2382,43675,186804,416916,727,1268,32207,31979,1301,1300,186826,387090,91061,39778,29465,158846,729,724,203492,203491,203490,32066,848,135625,538998,28050,33024,80840,28216,40544,506,165179,1224,36835,33038,1263076
Study 338/Experiment 2/Signature 2	NA	75682,846,84998,84999,304	119852,820,171550,1263,838,544448,31969,201174,85004,1678,28221,213115,194924,35832,447020,872,44748,1769729,2005519,990719,128827,526524,526525,239759,1730,626932,990721,1485,1302,244127,676517,1680,847,61170,84107,186807,1185408,74426,31953,102106	119852,820,171550,1263,838,544448,31969,201174,85004,1678,28221,213115,194924,35832,447020,872,44748,1769729,2005519,990719,128827,526524,526525,239759,1730,626932,990721,1485,1302,244127,676517,1680,847,75682,846,61170,84107,84998,84999,186807,1185408,74426,31953,102106,304
Study 370/Experiment 1/Signature 1	NA	NA	1301,1378,724,2745,117563	1378,117563,724,2745,1301
Study 377/Experiment 2/Signature 2	NA	59823,39777,1318	33031,230143,135079,31977,28134,651822,84109,419015,2049034,28136,310514,281920,186802,439703,158,671224,33033,895,1358,166,51160,2023260,28135,31969,28137,28131,28129,1969407,638849,143361,851,1596,114702,1926307,28124,187326,39778	33031,230143,135079,31977,28134,651822,84109,419015,2049034,28136,310514,281920,186802,439703,158,671224,33033,895,1358,166,51160,2023260,28135,31969,28137,28131,28129,1969407,638849,143361,851,1596,114702,1926307,59823,28124,187326,39777,1318,39778
Study 407/Experiment 1/Signature 2	NA	203691,1301,1300,28216	538,52228,1508421,43994,1716,1653,113286,843,649775,649777,508458,649776,44259,68298,72294,194,29547,213849,186828,940557,2701,1378,539003,1385,32207,1268,416916,80840,2037,136,203692,137,157,186826,91061,482,481,206351,1224	538,52228,1508421,43994,1716,1653,113286,843,649775,649777,508458,649776,44259,68298,72294,194,29547,213849,186828,940557,2701,1378,539003,1385,32207,1268,416916,80840,2037,136,203691,203692,137,157,1301,1300,186826,91061,482,481,206351,28216,1224

**Comment by tosfos** [comment] 2021-04-08 20:58
Are you able to easily send this data in a more structured format so we can see the separation between the columns? Maybe as a spreadsheet?

**Comment by lgeistlinger** [comment] 2021-04-12 17:14
Sure, here is a csv file that you can open eg in excel:

[inconsistent_sigs.csv](https://github.com/waldronlab/BugSigDB/files/6298558/inconsistent_sigs.csv)

**Comment by lgeistlinger** [comment] 2021-07-02 00:10
@tosfos is this still in the checks or are we leaving it at that and close?

**Comment by tosfos** [comment] 2021-07-05 14:11
We're still working on this. We'll bump up priority and try and complete it soon.

**Comment by tosfos** [comment] 2021-07-06 14:53
It looks like the import column of inconsistent_sigs.csv may be based on an older version of the import CSV. We had 3 versions and I believe that [this](https://github.com/waldronlab/BugSigDB/issues/19#issuecomment-749038827) is the final one. We created our own Python script to test the imported NCBIs against the exported ones and they all matched up, with the exception  that certain NCBI IDs are represented by text instead of an actual NCBI ID. Please let me know if you'd like us to document and send the code.

**Comment by lwaldron** [comment] 2021-07-09 14:17
I don't think documentation of the import is important because we'll never do it again, and its accuracy is confirmed except for these 16. As for these 16, I assumed that these setdiff values were probably all additions, and if so I've finished manually adding them, see below (it was fast because, as I learned, comma-separated NCBI IDs can be bulk-entered in the signature form!) @lgeistlinger could you check whether there were any deletions that needed to be made, or just check again? There is one below ([Study 286/Experiment 1/Signature 2](https://bugsigdb.org/Study_407/Experiment_1/Signature_2)) that I couldn't understand the diff output; @rimsha1 could you check this since you were the original curator? 

- [x] Study 5/Experiment 1/Signature 1 NA 1257,32066,84642 (added by @lwaldron)
- [x] Study 18/Experiment 1/Signature 1 NA 351091,89153 (added by @lwaldron)
- [x] Study 56/Experiment 3/Signature 1 NA 135858,33882,1378 
- [x] Study 150/Experiment 1/Signature 2 NA 186804,203491 
- [x] Study 165/Experiment 1/Signature 2 NA 174708,32207,186806 
- [x] Study 178/Experiment 3/Signature 1 NA 22,39948,1378,206349 
- [x] Study 274/Experiment 8/Signature 1 NA NA 1465756,2701,1578,165779,437755,28125,1678,47770 
- [x] Study 285/Experiment 3/Signature 1 NA 823,39778 
- [x] Study 295/Experiment 1/Signature 1 NA 119060,1257,1678,32066 
- [x] Study 307/Experiment 1/Signature 2 NA 135858,1318,729 
- [x] Study 338/Experiment 2/Signature 1 NA 33024,80840,506 
- [x] Study 338/Experiment 2/Signature 2 NA 75682,846,84998,84999,304 
- [x] Study 370/Experiment 1/Signature 1 NA NA 1301,1378,724,2745,117563 1378,117563,724,2745,1301
- [x] Study 377/Experiment 2/Signature 2 NA 59823,39777,1318 
- [x] Study 407/Experiment 1/Signature 2 NA 203691,1301,1300,28216 

- [ ] Study 286/Experiment 1/Signature 2 NA NA 1239,572511,1407607,574697,207244,102106,204516,1263,328814,39488,39496,1852369 328814,39488,207244,572511,574697,102106,39496,1239,1407607,1852369,204516,1263

**Comment by lgeistlinger** [comment] 2021-07-09 15:06
Sure, I'll check.

**Comment by lwaldron** [comment] 2021-07-09 15:24
Update, @ftzohra22 reviewed Study 286/Experiment 1/Signature 2 and it is correct and marked as reviewed, so these should all be correct now as long as none of the differences were deletions. Once you check @lgeistlinger go ahead and close.

**Comment by lgeistlinger** [comment] 2021-07-13 00:07
Ran another check and we are looking all good now. Closing this issue.

**Closed by lgeistlinger** 2021-07-13 00:07 UTC
Labels: priority
