### ISSUE TITLE
Study 784 Experiments not showing but exist

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDB#221] opened 2024-03-12 14:23 UTC
https://bugsigdb.org/Study_784 shows no experiments on the page but they do exist: https://bugsigdb.org/Study_784/Experiment_1

I tried refreshing the page under ... > Refresh but that did not resolve the issue.

**Comment by tosfos** [comment] 2024-03-12 17:10
This probably has the same cause as #196. We'll check this Study in particular, but a permanent solution has been elusive.

**Comment by tosfos** [comment] 2024-03-12 23:05
We re-saved the experiment page and it's showing up now. I'm not sure if you tried to refresh the Experiment page or only the Study page. In the future, that would be more likely to succeed.

We're going to keep researching how this happened.

**Comment by cmirzayi** [comment] 2024-05-30 13:15
@tosfos I'm not sure if this is the same bug but we're seeing something similar for https://bugsigdb.org/Study_1069 where https://bugsigdb.org/Study_1069/Experiment_3 and https://bugsigdb.org/Study_1069/Experiment_4 are not displaying. I tried refreshing both the study page and the experiment page and it's still not showing.

**Comment by fiddyhamma** [comment] 2024-06-01 21:12
@cmirzayi @tosfos 
Experiments 7 and 8 also have this issue 
https://bugsigdb.org/Study_1079

**Comment by Buraah** [comment] 2024-06-03 12:06
Hello @cmirzayi 
I am currently having the same issue. Experiments 4,5 and 6 are not showing but they exist.
Study link: https://bugsigdb.org/Study_940

**Comment by Scholarpat** [comment] 2024-06-05 17:24
Hello,

In this study, https://bugsigdb.org/Study_1013, experiments and signatures intermittently failed to display. Reloading the page sometimes resolves this issue, but sometimes they don't display after reloading.

**Comment by Scholarpat** [comment] 2024-06-06 18:10
Signatures for experiments 5, 6 and 7 are not displaying but exist; https://bugsigdb.org/Study_950

**Comment by Scholarpat** [comment] 2024-06-10 12:02
Signature 2 of experiment 1 in this study, https://bugsigdb.org/Study_901, is not also displaying but exist.

**Comment by Scholarpat** [comment] 2024-06-10 16:41
This study is also having the same issue;
https://bugsigdb.org/Study_915

Experiments 3 and 4 and their signatures are not showing but exist.

**Comment by Scholarpat** [comment] 2024-06-11 17:47
Signature 2 of experiment 1 here is not displaying;
https://bugsigdb.org/Study_890

**Comment by Scholarpat** [comment] 2024-06-18 12:54
Signature 1 of experiment 1, 2 and 3 are not displaying for this study;
https://bugsigdb.org/Study_1054

**Comment by Scholarpat** [comment] 2024-06-20 11:17
Signature 2 of experiment 4 is not displaying for this study;
https://bugsigdb.org/Study_1026

**Comment by Scholarpat** [comment] 2024-06-20 17:02
Experiments 2, 3 and 4 with their signatures are not displaying in this curation;
https://bugsigdb.org/Study_916

**Comment by tosfos** [comment] 2024-06-20 19:28
We'll check on it and see how we can resolve all of these issues permanently.

**Comment by Scholarpat** [comment] 2024-06-25 14:25
Signature 2 of experiments 1 and 3 are not displaying in this study;
https://bugsigdb.org/Study_1009

**Comment by Scholarpat** [comment] 2024-06-30 15:54
Signature 1 of experiment 6 is not displaying in this study;
https://bugsigdb.org/Study_997

**Comment by Scholarpat** [comment] 2024-07-05 09:21
Experiment 2 and its signature 1 is not displaying for this study;
https://bugsigdb.org/Study_1062

**Comment by Scholarpat** [comment] 2024-07-05 09:27
Hi @SvetlanaUP,

Here are the changes I made:

- **Study design:** Changed from 'time series / longitudinal observational' to 'Cross-sectional'.
- **Added:** Sequencing type and data transformation.
- **Statistical test:** Changed from 'Kruskall-Wallis, PERMANOVA, Spearman Correlation' to 'LEfSe'.
- **Confounders:** Edited out initially curated confounders (LEfSe does not control for confounders).
- **Signature description:** Altered.
- **Taxonomy update:** Changed 'Ruminococcaceae' to its heterotypic synonym 'Oscillospiraceae' in signature 1 of experiment 1.
- **Additional experiment:** Curated additional experiment 2 (and signature 1) which is not displaying. I've reported the issue.

This curation is completed.

Thank you!

**Comment by cmirzayi** [comment] 2024-07-18 13:16
I checked all of these and they seem to be appearing now so closing this issue.

**Comment by SvetlanaUP** [comment] 2024-08-02 12:39
@Scholarpat is facing the same issue again. Scholastica, please report it here.

**Comment by Scholarpat** [comment] 2024-08-02 12:45
Some signatures are not displaying in this study;
https://bugsigdb.org/Study_1018

Signature 1 and 2 of experiment 2
Signature 1 of experiments 3, 4 and 5

**Comment by Scholarpat** [comment] 2024-08-05 11:50
Signature 1 of experiments 11, 12 and 13  are not displaying in this study;
https://bugsigdb.org/Study_943

**Comment by tosfos** [comment] 2024-08-05 16:44
We have a fix in progress. We're hoping it will be resolved by Thursday.

**Comment by MyleeeA** [comment] 2024-08-13 10:46
Signatures 1 and 2 for Experiment 13 and Signature 2 for Experiment 14 in this study is not visible 
 https://bugsigdb.org/Study_1086

**Comment by MyleeeA** [comment] 2024-08-13 14:35
I don’t know if this is a temporal fix or if it will work for other studies with same issues, but I noticed, when I edited an experiment with invisible signatures and saved the page the signatures appeared.

Currently all the signatures are visible for this study https://bugsigdb.org/Study_1086

**Comment by fiddyhamma** [comment] 2024-08-16 09:49
I added a signature for experiment 7 but it's not showing 
https://bugsigdb.org/Study_1079

**Comment by tosfos** [comment] 2024-08-28 22:22
We're in a catch-22 here. None of the versions of the extension we use for dependency updates will cover all situations. But the present situation is clearly not workable. We're going to update to the latest version of the extension which will work better overall, and then we'll improve it.

**Comment by tosfos** [comment] 2024-08-29 14:59
The server is being restarted as part of this work. It will be down for a couple of minutes.

**Comment by tosfos** [comment] 2024-08-30 18:33
This issue should be basically resolved. I'll follow up with more details.

**Comment by cmirzayi** [comment] 2024-09-09 17:02
This issue is continuing. Today's export is missing nearly 1000 records. This bug has become a critical issue that is impacting our ability to work with the BugSigDB data.

**Comment by tosfos** [comment] 2024-09-09 17:47
Please provide more details. Is it the Signature CSV?

**Comment by tosfos** [comment] 2024-09-09 19:49
[Signatures.csv](https://github.com/user-attachments/files/16935731/Signatures.csv)
We are seeing that the CSV download link is returning a different number of rows each time it is run. I attached an updated CSV that has all the Signatures. We'll research a better solution.

**Comment by cmirzayi** [comment] 2024-09-10 19:34
@tosfos Thank you so much. It does seem to be resolved. I was wondering if/when (hopefully) BugSigDB doubles in size over the next few years, are we going to run into this issue again?

Just wondering if there's any groundwork or processes we can put into play in the near to mid-future to prevent this from becoming a problem a few years down the line?

**Comment by seandavi** [comment] 2024-09-10 20:54
I think that @jwokaty's idea of tracking export sizes with an alert if thing break is a good one. See https://github.com/waldronlab/BugSigDBExports/issues/34 for discussion.

**Comment by cmirzayi** [comment] 2024-09-10 21:30
Thanks Sean. I agree. Jen and I met earlier today to discuss this issue and how we can detect it faster going forward. They and I are working on implementing some detection solutions for the exports and bugsigdbr. However, since this seems to have stemmed from a resource issue upstream of the exports, I wanted to check to see if there was anything else we can do to ameliorate this once and future issue upstream as well.

**Comment by cmirzayi** [comment] 2024-09-25 19:41
@tosfos Unfortunately the issue is not resolved. I just noticed the signatures.csv is once again returning differing rows each time it's run. I ran it in the past 10 minutes and got 2081 rows, 4106 rows, and 5352 rows.

**Comment by tosfos** [comment] 2024-09-25 23:31
We adjusted the settings again and did a restart. It looks like the problem is resolved for now, but we need to do more research because it seems our solution is not permanent.

**Comment by tosfos** [comment] 2024-09-29 14:55
We  believe a permanent solution is in place as of yesterday afternoon. We're still monitoring.

**Comment by tosfos** [comment] 2024-10-02 20:40
Have any issues been seen since 9/28?

**Comment by cmirzayi** [comment] 2024-10-02 20:49
Not that I have observed. @jwokaty you are more closely monitoring this. Anything you've noticed?

**Comment by jwokaty** [comment] 2024-10-02 20:55
No issues yet. Let's watch it over the next two weeks.

**Comment by tosfos** [comment] 2024-11-14 19:10
Let's close this and create a new issue if anything happens.

**Closed by tosfos** 2024-11-14 19:10 UTC
Labels: bug
